baseURL = "https://jibhranlimon96.github.io/my_launchx_blog/#my-launch-x-blog-bit%C3%A1cora-de-viaje-"
languageCode = "en-us"
title = "BitÃ¡cora de Viaje Jibhran Aguilar Limon (SOY EL MEJOR)"
theme = "hugo-winston-theme"
relativeURLs = true
canonifyURLs = true

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[params]
  google_analytics_id = ""
  # Hey Explorer aquÃ­ pon tu twitter ðŸ‘‡
  twitter_handle = "@JibhranL"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addFrame = true
  addDot = true
